// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA-BJft-jd8nlzG_S-cYbpM5GRa43PC0g',
    appId: '1:905156797676:web:10b009c5fd6a34315eb1c9',
    messagingSenderId: '905156797676',
    projectId: 'delabel-net-1',
    authDomain: 'delabel-net-1.firebaseapp.com',
    storageBucket: 'delabel-net-1.appspot.com',
    measurementId: 'G-7NJJ0ZX4TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw5PnIw_e5rPdK38_SRaMPqlj5kGMSrmk',
    appId: '1:905156797676:android:d9d6b956b69bafd55eb1c9',
    messagingSenderId: '905156797676',
    projectId: 'delabel-net-1',
    storageBucket: 'delabel-net-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsEocuLMEQ2GcrY375q50tevKDgYYfRMY',
    appId: '1:905156797676:ios:b26d839c672b06455eb1c9',
    messagingSenderId: '905156797676',
    projectId: 'delabel-net-1',
    storageBucket: 'delabel-net-1.appspot.com',
    iosClientId: '905156797676-qqjp4s937e5r2oesgg1g1d7s1j88th2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.delabelV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsEocuLMEQ2GcrY375q50tevKDgYYfRMY',
    appId: '1:905156797676:ios:037a85a2da7db85a5eb1c9',
    messagingSenderId: '905156797676',
    projectId: 'delabel-net-1',
    storageBucket: 'delabel-net-1.appspot.com',
    iosClientId: '905156797676-ve9ifjv6v5j7qjs0q8feqr9a7s48n15c.apps.googleusercontent.com',
    iosBundleId: 'com.example.delabelV3.RunnerTests',
  );
}
